### ISSUE TITLE
Create an header section

### ISSUE THREAD

**Issue by Adelabuadeleke** [salstein/my-e-commerce#25]
create an header section, like we do see in other e-commerce web app(e.g amazon), it could be or include a slider of some products, promotions, discount announcement

**Comment by Adelabuadeleke** [comment]
Hello @salstein  I'd love to be assigned to this issue.

**Comment by Adelabuadeleke** [comment]
@salstein  kindly assign this to me.

**Comment by himanchal08** [comment]
i would like to work on this issue it seems doable
i will try my best to implement it
